const invoice_1 = {
  addedItems: 2,
  city: 'London',
  cl_city: 'New Castle',
  cl_country: 'England',
  cl_email: 'jess.dav@example.com',
  cl_invoice_date: '22.08.2021',
  cl_name: 'Jessica Davis',
  cl_post_code: '32-546',
  cl_street: 'Beltrand St. 23/75',
  country: 'England',
  id: '#INV37X24',
  item_name_1: 'Sofa',
  item_name_2: 'Armchair',
  item_price_1: '899',
  item_price_2: '550',
  item_quan_1: '2',
  item_quan_2: '4',
  item_total_1: '1798$',
  item_total_2: '2200$',
  itemsContainer: [
    ['Sofa', '2', '899', '1798$'],
    ['Armchair', '4', '550', '2200$'],
  ],
  payment_term: '21',
  post_code: '21-431',
  project_descrip: '',
  status: 'pending',
  street: 'Baker St. 74/32',
  total: 3998,
};

const invoice_2 = {
  addedItems: 1,
  city: 'London',
  cl_city: 'Washington',
  cl_country: 'United States of America',
  cl_email: 'barney.john@example.com',
  cl_invoice_date: '14.07.2021',
  cl_name: 'Barney Johnson',
  cl_post_code: '98-132',
  cl_street: 'Black St. 99/43',
  country: 'England',
  id: '#INV04X12',
  item_name_1: 'Recruitment service',
  item_price_1: '8000',
  item_quan_1: '1',
  item_total_1: '8000$',
  itemsContainer: [['Recruitment service', '1', '8000', '8000$']],
  payment_term: '14',
  post_code: '65-214',
  project_descrip: '',
  status: 'paid',
  street: 'Churchill St. 23B/4',
  total: 8000,
};

const invoice_3 = {
  addedItems: 1,
  city: 'Washington',
  cl_city: 'London',
  cl_country: 'England',
  cl_email: 'caroline.montgomery',
  cl_invoice_date: '29.08.2021',
  cl_name: 'Caroline Montgomery',
  cl_post_code: '78-325',
  cl_street: 'Blue St. 41/5',
  country: 'USA',
  id: '#INV72X25',
  item_name_1: 'Book',
  item_price_1: '39',
  item_quan_1: '5',
  item_total_1: '195$',
  itemsContainer: [['Book', '5', '39', '195$']],
  payment_term: '14',
  post_code: '91-416',
  project_descrip: '',
  status: 'pending',
  street: 'Churchill St. 37/32',
  total: 195,
};

const invoice_4 = {
  addedItems: 1,
  city: 'Washington',
  cl_city: 'London',
  cl_country: 'England',
  cl_email: 'bob.smith1978@example.com',
  cl_invoice_date: '29.08.2021',
  cl_name: 'Bob Smith',
  cl_post_code: '78-325',
  cl_street: 'Blue St. 41/5',
  country: 'USA',
  id: '#INV99X99',
  item_name_1: 'Window',
  item_price_1: '1399',
  item_quan_1: '9',
  item_total_1: '12591$',
  itemsContainer: [['Window', '9', '1399', '12591$']],
  payment_term: '14',
  post_code: '91-416',
  project_descrip: '',
  status: 'paid',
  street: 'Churchill St. 37/32',
  total: 12591,
};

export const randomData = [invoice_1, invoice_2, invoice_3, invoice_4];
